### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by psntr** [stephane-vanraes/sveltekit-sanity-starter#1]
Hi!

I saw your post on reddit and wanted to give it a try for a project, but I'm actually struggling to make the previewMode available. When I add the URL params to my url for instance locally: `http://localhost:5173/?preview_token=myRandomToken` I dont' see the preview bar nor the drafts content. 

The `.env` is at the root of my folder and connexion to the Sanity content lake works, but it seems like the URL params `?preview_token` doesn't have effect.

**Comment by stephane-vanraes** [comment]
I have been switching between `preview_token` and `preview-token` while setting up this template and seem to have landed on saying one thing in the readme and another one in the code.

You can change to the want you want to use here https://github.com/stephane-vanraes/sveltekit-sanity-starter/blob/8a5a203e610a56d2804049b5b2384836ca988056/src/lib/sanity/client.server.ts#L23 

(I pushed a change just now so it is consistent)

On another note, what Reddit article are you talking about ? I don't use it, so somebody else must have written it :)

**Comment by psntr** [comment]
Awesome, thank you for the fast reply, now I can see the draft content as well as the preview bar. 

Regarding the reddit, my bad was maybe just a good old'google, I follow the reddit channel about svelte and there are really good starter for sveltekit overthere :) anyway, many thanks really excited to dig further into Sveltekit!
