### ISSUE TITLE
Deploying issue on Vercel with PUBLIC_SANITY_PROJECT_ID

### ISSUE THREAD

**Issue by psntr** [stephane-vanraes/sveltekit-sanity-starter#2]
Hey there,

I'm finally read to try this project on Vercel, but I got this error when I'm trying to build it on Vercel.

```
"PUBLIC_SANITY_PROJECT_ID" is not exported by "$env/static/public", imported by "src/lib/sanity/client.server.ts".
--
22:02:02.476 | file: /vercel/path0/src/lib/sanity/client.server.ts:4:1
```
Do I have to push my .env file to github to fix this issue or run something specific beforehand?

Any help would be much appreciated!

**Comment by stephane-vanraes** [comment]
Locally you can use the `.env` file (**never push this file**)

How you set them in production depends a lot on your hosting, I haven't used Vercel yet myself, but according to the documentation this should be available somewhere in your project settings:

https://vercel.com/docs/concepts/projects/environment-variables

~I am not 100% sure why they are marked as `public` though, the setup as it is assumes all connections to Sanity happen on the server, in that case you can drop the `PUBLIC_` part and import from `$env/static/private`. Likely this is better as it will prevent from leaking your keys to the clients.~

nvm, my mistake you need the public key for the image helper :)

**Comment by psntr** [comment]
Hey Stephane!

Thank you for pointing me to the right direction, also first time using Vercel and I didn't know about the .env and the settings field in Vercel. It makes a lot of sense now. 

I added the value in Vercel as environment variables and now it works! Just to make sure, prefixing with PUBLIC is just for you to make sure that it's a public accessible key right? It doesn't influence the code itself?

**Comment by stephane-vanraes** [comment]
the keys that are marked with `PUBLIC` are considered "safe" to use client side as well as they _can_ (if you import them) be included in the code send to the client and anyone with enough knowledge can read that code.
So to avoid sending secret keys and tokens do not prefix them.

In the case of this template, the dataset and project id are public, but the token isn't.  Without the token the other information is kind of worthless so you are ok.

**Comment by psntr** [comment]
Thank you for your patience explaining these basics :) 

Not related to this issue and it's an issue itself but I think you could swap the newest api for Sanity:
`apiVersion: '2021-08-31'` -> `'2021-10-21'`

Again thanks for this great starter!
